# docker stop keycloak_dev && docker rm keycloak_dev && docker-compose -f docker-compose-dev.yml up
# docker-compose -f docker-compose-dev.yml up
# docker-compose -f docker-compose-dev.yml down
# docker exec -it keycloak_dev sh -c "cat opt/jboss/keycloak/themes/new-theme/login/resources/css/login.css"

version: '3.5'
services:
  keycloak_dev:
    container_name: keycloak_dev
    image: quay.io/keycloak/keycloak:19.0.3
    command: ["start-dev"]
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_IMPORT: /tmp/realm-export.json

#      KEYCLOAK_LOGLEVEL: DEBUG
#      KEYCLOAK_THEME_CACHE_THEMES: "false"
#      KEYCLOAK_CONFIG_FILE: /opt/jboss/keycloak/standalone/configuration/keycloak.server.json
#      KEYCLOAK_SERVER_OPTS: "-Dkeycloak.theme.cacheThemes=false -Dkeycloak.theme.cacheTemplates=false -Dkeycloak.theme.staticMaxAge=-1"

    volumes:
#      - ./realm-export.json:/tmp/realm-export.json
#      - ./keycloak.server.json:/opt/jboss/keycloak/standalone/configuration/keycloak.server.json
      - ../themes/new-theme:/opt/jboss/keycloak/themes/new-theme

    networks:
      - keycloak_net

networks:
  keycloak_net:
    name: keycloak_net
    driver: bridge

